//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book_Parts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book_Parts()
        {
            this.User_Books = new HashSet<User_Books>();
        }
    
        public int Book_PartID { get; set; }
        public string BookName { get; set; }
        public Nullable<int> BookID { get; set; }
        public string Image { get; set; }
        public Nullable<int> BookNumber { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Published_Date { get; set; }
        public Nullable<int> AuthorID { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> Rate { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Book Book { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Books> User_Books { get; set; }
    }
}
