//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Books
    {
        public int User_BooksID { get; set; }
        public int UserID { get; set; }
        public Nullable<int> Book_PartID { get; set; }
        public Nullable<int> BookID { get; set; }
        public Nullable<bool> HasParts { get; set; }
        public Nullable<bool> IsBought { get; set; }
        public Nullable<int> BookNums { get; set; }
        public Nullable<double> TotalPrice { get; set; }
        public Nullable<System.DateTime> Bought_Date { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Book_Parts Book_Parts { get; set; }
        public virtual User User { get; set; }
    }
}
